### ISSUE TITLE
Jira direct message broken

### ISSUE THREAD

**Issue by kaiomagalhaes** [codelittinc/roadmap#11]
```
(node:52) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of null
    at default (file:///app/src/Flows/Repository/Github/ClosePullRequestFlow/sendJiraConfirmation.js:4:48)
    at file:///app/src/Flows/Repository/Github/ClosePullRequestFlow/index.js:57:9
    at Array.forEach (<anonymous>)
    at Function.start (file:///app/src/Flows/Repository/Github/ClosePullRequestFlow/index.js:55:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async create (file:///app/src/controllers/FlowsController.js:35:9)`
```

**Comment by kaiomagalhaes** [comment]
May be solved by #3
